id: IDB615F00
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-22T19:30:12+00:00'
last_modified: '2022-06-08T13:10:06.835047+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W8LS18125
  title: ལྷ་མོ་འོད་ཟེར་ཅན་མའི་སྒོ་ནས་བཟློག་བསྒྱུར་བྱ་ཚུལ་སོགས།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    18EB:
      image_group_id: I8LS18144
      title: ''
      total_pages: 102
      order: 1
      base_file: 18EB.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
