id: IDB615F00
legacy_id: P010379
ocr_import_info:
  bdrc_scan_id: W8LS18125
  source: bdrc
  ocr_info:
    timestamp: '2020-03-22T19:29:32'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-04T04:06:40.628085+00:00'
last_modified: 2022-09-04 12:06:47.453826
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W8LS18125
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW8LS18125
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: ལྷ་མོ་འོད་ཟེར་ཅན་མའི་སྒོ་ནས་བཟློག་བསྒྱུར་བྱ་ཚུལ་སོགས།
statistics:
  ocr_word_mean_confidence_index: 0.43720007865096755
  ocr_word_median_confidence_index: 0.3499999940395355
quality: null
bases:
  I8LS18144:
    source_metadata:
      id: http://purl.bdrc.io/resource/I8LS18144
      total_pages: 102
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I8LS18144.txt
    statistics:
      ocr_word_median_confidence_index: 0.3499999940395355
      ocr_word_mean_confidence_index: 0.43720007865096755
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
